from __future__ import annotations

import json

import streamlit as st

from app.ui.components import render_kpi_grid, render_section_header
from app.ui.theme import inject_theme
from config.settings import get_settings
from core.pipeline import build_portfolio_snapshot


def main() -> None:
    settings = get_settings()
    st.set_page_config(
        page_title="Samuel Maia Analytics Platform",
        page_icon="SM",
        layout="wide",
    )
    inject_theme()

    st.title("Analytics Portfolio Platform")
    st.caption("Enterprise-style decision support surface for analytics engineering and data products.")

    snapshot = build_portfolio_snapshot(settings)

    render_section_header(
        "Executive Snapshot",
        "Operationally structured view of portfolio metrics, quality signals, and AI-assisted commentary.",
    )
    render_kpi_grid(snapshot["semantic_metrics"])

    render_section_header("Repository Registry", "Selective integration of local reference repositories.")
    st.dataframe(snapshot["repository_registry"], width="stretch", hide_index=True)

    render_section_header("Data Quality", "Current governed checks for the sample analytical surface.")
    st.json(snapshot["quality_report"])

    render_section_header("Semantic Metrics Catalog", "Definitions and domain rollups used by the platform.")
    st.json(snapshot["metric_catalog"])

    render_section_header("GenAI Insight Layer", "Analytics-oriented drafts generated by a provider-agnostic service.")
    st.markdown(snapshot["genai_insight"]["narrative"])
    st.caption(f"Provider status: {snapshot['genai_insight']['provider_status']}")
    st.dataframe(
        [
            {
                "use_case": artifact["use_case"],
                "generation_mode": artifact["generation_mode"],
                "provider_status": artifact["provider_status"],
                "prompt_reference": artifact["prompt_reference"],
            }
            for artifact in snapshot["genai_outputs"].values()
        ],
        width="stretch",
        hide_index=True,
    )

    render_section_header("Observability Event", "Latest structured event emitted by the pipeline.")
    st.code(json.dumps(snapshot["observability_event"], indent=2), language="json")


if __name__ == "__main__":
    main()
